src/ReactiveUI.Validation/Contexts/ValidationContext.cs
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Removes the dependency on `ReactiveUI.Legacy` namespace.
**What is the current behavior? (You can also link to an open issue here)**
ReactiveUI.Validation uses `ReactiveList` which is now obsolete.
**What is the new behavior (if this is a feature change)?**
ReactiveUI.Validation uses DynamicData `SourceList<T>` now.
Probably nothing, let's see CI checks!
=> Replace ReactiveList with SourceList

README.md
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
Added codecov, azure pipelines and nuget badges.
What is the current behavior? (You can also link to an open issue here)
There are no badges in README.md now!
What is the new behavior (if this is a feature change)?
Badges are present.
What might this PR break?
Nothing.
=> housekeeping: Add Badges

README.md
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Readme updates include:
- Including a new section for Android extensions and a sample.
- A simplified generic sample for validations.
**What is the current behavior? (You can also link to an open issue here)**
The sample is too complex with many references.
**What is the new behavior (if this is a feature change)?**
Simplified sample.
I would like to add a sample for `ValidationHelper` property in a ViewModel and binding to that from the View, but I think that is unnecessary.
=> Housekeeping: Improved readme samples and descriptions.

src/ReactiveUI.Validation.Tests/ValidationContextTests.cs, src/ReactiveUI.Validation/Components/BasePropertyValidation.cs
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Fix null reference when registering validations with different lambda body name.
**What is the current behavior? (You can also link to an open issue here)**
If you register a validation with "viewModel => viewModel.Name" and in the view you register with "vm => vm.Name", it will throw an Exception due that is comparing the full body name.
See bug: https://github.com/reactiveui/ReactiveUI.Validation/issues/16
Nothing.
=> Fix #16: Null reference with lambdas

src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.cs, src/ReactiveUI.Validation.Tests/Models/TestView.cs, src/ReactiveUI.Validation.Tests/ValidationContextTests.cs, src/ReactiveUI.Validation/Formatters/SingleLineFormatter.cs
Now `SingleLineFormatter` uses the " " character by default for validation error messages concatenation. I think this behavior is what a new user would expect from the library.
Before, it just concatenated the error message texts. This caused the messages to be glued to each other.
Now the messages are concatenated using the whitespace character. This can be easily overriden by passing a custom `SingleLineFormatter` to `BindValidation`, but probably using the whitespace character out-of-box will make the library more developer-friendly.
Sometimes when running unit tests locally I get the following exception thrown in random tests:
``` …
```
=> Use Space char as default delimiter

README.md
`README.md` file update.
Currently there is a typo in the example, so mostly this PR is aimed to fix the following line:
```cs
// The property will create a new context each time it is accessed.
// This could cause issues if someone copy-pastes this line.
public ValidationContext ValidationContext => new ValidationContext();
```
Fixed the typo, added shields downloads badge, added logo, added contributing section.
Nothing.
=> Fix typos, add logo, add downloads badge to README

README.md, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net472.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.netcoreapp2.1.approved.txt, src/ReactiveUI.Validation.Tests/Models/IndeiTestView.cs, src/ReactiveUI.Validation.Tests/Models/IndeiTestViewModel.cs, src/ReactiveUI.Validation.Tests/Models/TestViewModel.cs, src/ReactiveUI.Validation.Tests/NotifyDataErrorInfoTests.cs, src/ReactiveUI.Validation/Abstractions/IValidatableViewModel.cs, src/ReactiveUI.Validation/Components/BasePropertyValidation.cs, src/ReactiveUI.Validation/Extensions/SupportsValidationExtensions.cs, src/ReactiveUI.Validation/Extensions/ViewForExtensions.cs, src/ReactiveUI.Validation/Helpers/ReactiveValidationObject.cs, src/ReactiveUI.Validation/Platforms/Android/ViewForExtensions.cs, src/ReactiveUI.Validation/ValidationBindings/ValidationBinding.cs, src/ReactiveUI.Validation/ValidationBindings/ValidationBindingEx.cs
This PR introduces a set of two major changes, one of them is breaking:
- The `ISupportsValidation` interface is refactored into `IValidatableViewModel`, to match the new ReactiveUI 10 [activation-related things naming](https://github.com/reactiveui/ReactiveUI/releases/tag/10.0.1), e.g. `IActivatableViewModel`;
- The abstract base class `ReactiveValidationObject<TViewModel>` is added, which encapsulates `INotifyDataErrorInfo` support for platforms such as WPF, Avalonia, Xamarin.Forms. Closes https://github.com/reactiveui/ReactiveUI.Validation/issues/37
Currently, `INotifyDataErrorInfo` isn't supported and `ISupportsValidation` isn't renamed.
`INotifyDataErrorInfo` is supported, …
=> Support INotifyDataErrorInfo, rename ISupportsValidation

src/global.json
Build fails due to .Net Core SDK which is no longer available on hosted agent. Aligned this file with other JSONs from the Reactive UI family.
Removes SDK definition
Updates MSBuild.SDK.Extras version
The build is failing on the agent.
The build should work again.
The build may still be broken after this.
=> Housekeeping: Update MSBuild.Sdk.Extras

src/ReactiveUI.Validation.Tests/NotifyDataErrorInfoTests.cs, src/ReactiveUI.Validation/Helpers/ReactiveValidationObject.cs
Fix concurrency issues related to `INotifyDataErrorInfo.ErrorsChanged` event invocation.
Currently, the `INotifyDataErrorInfo.ErrorsChanged` event is raised too often, each time any of the `ValidationContext.ValidationStatusChange` and `ReactiveObject.Changed` observables signal. The `ValidationStatusChange` observable emits new values when validation status changes for any of the properties, and the `ReactiveObject.Changed` event is raised when any property changes. Although this approach allows us to obtain the name of the changed property, this results in unnecessary calls to `ErrorsChanged` and has concurrency issues (e.g. the `INotifyDataErrorInfo.GetErrors` gets called when validation error messages …
=> Fix ReactiveValidationObject<T> concurrency issues

README.md, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net472.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.netcoreapp2.1.approved.txt, src/ReactiveUI.Validation/Components/Abstractions/IPropertyValidationComponent.cs, src/ReactiveUI.Validation/Components/Abstractions/IValidatesProperties.cs, src/ReactiveUI.Validation/Components/BasePropertyValidation.cs, src/ReactiveUI.Validation/Components/ModelObservableValidation.cs, src/ReactiveUI.Validation/Components/ModelObservableValidationBase.cs, src/ReactiveUI.Validation/Helpers/ReactiveValidationObject.cs, stylecop.json
- new overload for this.ValidationRule extension method that takes a Func<ViewModel, IObservable<bool>> as well as a lambda that states which property the rule refers to.
- new common base interface `IPropertyValidationComponent<TViewModel>` for `BasePropertyValidation` and `ModelObservableValidationBase` to access `ContainsPropertyName`/`IsValid`/`Text` uniformly (in `INotifyDataErrorInfo.GetErrors` implementation)
- new abstract base class ModelObservableValidationBase (to later on generate more overloads analog to BasePropertyValidation by .tt file)
Until now INotifyDataErrorInfo did not work in conjunction with using the Func<ViewModel, IObservable<bool>> overload of the ValidationRule extension method. …
=> ModelObservableValidation + INotifyDataErrorInfo

src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net472.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.netcoreapp2.1.approved.txt, src/ReactiveUI.Validation.Tests/Models/IndeiTestViewModel.cs, src/ReactiveUI.Validation.Tests/NotifyDataErrorInfoTests.cs, src/ReactiveUI.Validation/Extensions/SupportsValidationExtensions.cs
- adds a testcase checking for the functionality of INDEI.GetErrors in context with ModelObservableValidation + property lambda
- adds the corresponding extension method (ValidationRule)
- no test
- no extension method
- test
- extension method
nothing, hopefully
=> extension and testcase for new ModelObservableValidation

src/Directory.build.targets, src/ReactiveUI.Validation/Contexts/ValidationContext.cs
ValidationContext uses RxApp.TaskpoolScheduler instead of RxApp.MainThreadScheduler for WPF and WinForms (NET_461 and NETCOREAPP).
Fixes #34
Fixes #63
**Current workarounds:**
1. public MainViewModel() : base(RxApp.TaskpoolScheduler)
2. public class MainWindowModel : ReactiveObject, IValidatableViewModel
public ValidationContext ValidationContext { get; } = new
ValidationContext(RxApp.TaskpoolScheduler);
Quote #34
> When having multiple validation rules, I get an IndexOutOfRangeException at Runtime. Both validation rules work when they are enabled individually.
> As I see it, the ValidationContext.Add() method adds validations to the _validationSource but not to the _validations readonly observable …
=> Use TaskpoolScheduler for WPF/WF ValidationContext

src/ReactiveUI.Validation/Helpers/ReactiveValidationObject.cs
Bug fix
Don't know
INotifyDataError can pass null or an empty string to the GetErrors method. This will cause an exeception within the code atm since its calls GetType().GetMember(propertyName) whether propertName is null or not. The code fixes this by checking for null and then notifies for 'entity-level errors.' if so (in line with the documentation).
It also caches the member-name/property-name mappings in a dictionary for faster future retrieval.
=> Added support for GetErrors parameter being null

samples/LoginApp.Avalonia/Views/SignUpView.xaml.cs, samples/LoginApp.WinForms/Views/SignUpView.cs, samples/LoginApp.Wpf/Views/SignUpView.xaml.cs, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net472.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.netcoreapp3.1.approved.txt, src/ReactiveUI.Validation.Tests/ValidationBindingTests.cs, src/ReactiveUI.Validation/Extensions/ViewForExtensions.cs, src/ReactiveUI.Validation/Platforms/Android/ViewForExtensions.cs, src/ReactiveUI.Validation/ValidationBindings/ValidationBinding.cs
Since https://github.com/reactiveui/ReactiveUI.Validation/pull/103 we support custom `IValidationTextFormatter`s in `BindValidation`, so this PR adds a way to override the default validation text formatter. With these changes, we are still using `SingleLineFormatter.Default`, but also try to resolve the `IValidationTextFormatter<string>` from `Locator.Current`. Also, this PR adds a few tests for validation bindings used in platform-specific `BindValidation` extension methods (e.g. in [`ViewForExtensions` in Android](https://github.com/reactiveui/ReactiveUI.Validation/blob/main/src/ReactiveUI.Validation/Platforms/Android/ViewForExtensions.cs#L47)) and improves XML docs.
Currently, there is no way to override …
=> Try Resolve a Default Formatter from Splat.Locator

src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net472.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.netcoreapp3.1.approved.txt, src/ReactiveUI.Validation.Tests/Models/ISampleViewModel.cs, src/ReactiveUI.Validation.Tests/Models/SampleView.cs, src/ReactiveUI.Validation.Tests/Models/SampleViewModel.cs, src/ReactiveUI.Validation.Tests/ValidationBindingTests.cs, src/ReactiveUI.Validation/Extensions/ValidatableViewModelExtensions.cs, src/ReactiveUI.Validation/Extensions/ViewForExtensions.cs, src/ReactiveUI.Validation/Platforms/Android/ViewForExtensions.cs, src/ReactiveUI.Validation/ValidationBindings/ValidationBinding.cs
Currently, ReactiveUI.Validation doesn't support creating `ValidationRule`s for objects that don't inherit from a `ReactiveObject`. Also, binding to `IViewFor<IReactiveObject>` via `BindValidation` isn't supported. However, there may be cases, when one needs to use an interface as a type parameter in `IViewFor` (e.g. `IViewFor<IViewModel>`). Also, some folks may decide to use a custom `IReactiveObject` implementation e.g. in case if they use ReactiveUI with MvvmCross, Prism, etc. So this PR changes the generic type constraint from `: ReactiveObject` to `: class, IReactiveObject` and adds a few tests for this.
Currently, ReactiveUI.Validation doesn't support binding to `IReactiveObject`s.
**What is the new …
=> Support Binding to IReactiveObject's

samples/LoginApp/ViewModels/SignUpViewModel.cs, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net472.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.netcoreapp3.1.approved.txt, src/ReactiveUI.Validation/Components/Abstractions/IPropertyValidationComponent.cs, src/ReactiveUI.Validation/Components/Abstractions/IValidatesProperties.cs, src/ReactiveUI.Validation/Helpers/ReactiveValidationObject.cs
This PR deprecates `ReactiveValidationObject<TViewModel>` in favor of just `ReactiveValidationObject`. The non-generic methods of core ReactiveUI.Validation interfaces were moved to the new non-generic interfaces in order to support non-generic property validation LINQ queries. This allows getting rid of type parameters in `ReactiveValidationObject` and using a bit shorter syntax.
Currently, in order to support `INotifyDataErrorInfo` notifications, one should inherit from `ReactiveValidationObject<T>`.
```cs
// Currently, the view model type should be always used as the generic type parameter.
public class SampleViewModel : ReactiveValidationObject<SampleViewModel> { }
```
Now, …
=> feature: Deprecate ReactiveValidationObject<T> in Favor of Just ReactiveValidationObject

samples/LoginApp.Avalonia/Views/SignUpView.xaml, samples/LoginApp/ViewModels/SignUpViewModel.cs
This PR updates our sample app to use the new `ValidationRule` overloads that work with `IObservable<TState>` streams.
Currently, we aren't showing the benefits of using the `IObservable<TState>` overloads of `ValidationRule`s. Also, we aren't showing how to use the concise `ValidationRule` overload that accepts an `IObservable<bool>`.
Now, we show how to do complex asynchronous validation with user input throttling.
Nothing.
=> refactor: Update the LoginApp to use Newer ValidationRule Overloads

README.md
This PR updates `README.md` with additional notes regarding up-to-date ReactiveUI.Validation features. This PR documents the changes introduced in https://github.com/reactiveui/ReactiveUI.Validation/pull/119 and https://github.com/reactiveui/ReactiveUI.Validation/pull/118, including the API changes and new `ValidationRule` overloads.
Currently, the docs in `README.md` are a bit outdated.
Now, the docs in `README.md` should be up-to-date.
Nothing. However, we may need to publish a new release for our NuGet to match the documentation.
=> housekeeping: Update the Documentation and Code Snippets in README

src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net472.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.netcoreapp3.1.approved.txt, src/ReactiveUI.Validation.Tests/ModelObservableTests.cs, src/ReactiveUI.Validation.Tests/ObservableValidationTests.cs, src/ReactiveUI.Validation.Tests/ReactiveUI.Validation.Tests.csproj, src/ReactiveUI.Validation/Components/Abstractions/IPropertyValidationComponent.cs, src/ReactiveUI.Validation/Components/Abstractions/IValidatesProperties.cs, src/ReactiveUI.Validation/Components/BasePropertyValidation.cs, src/ReactiveUI.Validation/Components/ModelObservableValidation.cs, src/ReactiveUI.Validation/Components/ObservableValidation.cs, src/ReactiveUI.Validation/Extensions/ValidatesPropertiesExtensions.cs, src/ReactiveUI.Validation/Extensions/ValidationContextExtensions.cs
This PR deprecates the generic `IPropertyValidationComponent<TViewModel>` and `IValidatesProperties<TViewModel>` in favor of the non-generic version of these interfaces, namely `IPropertyValidationComponent` and `IValidatesProperties`. The reasoning for this change was described in detail by @thargy in https://github.com/reactiveui/ReactiveUI.Validation/pull/118#issuecomment-708322698
> Commit 1565d37, updated `IValidatesProperties`, splitting it into generic/non-generic versions.  The generic version now contains solely the problematic <...> I say problematic, as implementing such an interface is non-trivial for authors intending to extend validation rules outside the library. The current implementation within the library is always the same …
=> refactor: Deprecate Generic IValidatesProperties<T>

src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net472.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.netcoreapp3.1.approved.txt, src/ReactiveUI.Validation.Tests/ValidationContextTests.cs, src/ReactiveUI.Validation/Contexts/ValidationContext.cs, src/ReactiveUI.Validation/Extensions/ValidatableViewModelExtensions.cs
This PR implements a feature described in https://github.com/reactiveui/ReactiveUI.Validation/issues/71
Currently, there is no `ClearValidationRule` extension method.
Now, there are two `ClearValidationRule` extension methods, one of them removes all validations from a context, and another one accepts a property expression selector and removes only those validations that reference the specified property.
Nothing.
Fixes  https://github.com/reactiveui/ReactiveUI.Validation/issues/71
=> feature: Add ClearValidationRules Extension Methods

README.md, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net472.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.netcoreapp3.1.approved.txt, src/ReactiveUI.Validation.Tests/ObservableValidationTests.cs, src/ReactiveUI.Validation/Extensions/ValidationContextExtensions.cs, src/ReactiveUI.Validation/States/ValidationState.cs, src/ReactiveUI.Validation/ValidationBindings/ValidationBinding.cs
This is discussed in https://github.com/reactiveui/ReactiveUI.Validation/pull/130#issuecomment-710691834.  Essentially, with the obsolescence of `Component` from `ValidationState` then the most common 'valid' state is identical and so should be exposed as a static readonly property.  This decreases memory utilisation.
The same object risks being created repeatedly in common usage.
Consumers can provide the static singleton instance.
All impacts relate to the now obsolete `Component` property, and could result in `NullReferenceExceptions` being thrown where consumers previously relied on the component.  This is considered highly unlikely, and …
=> Refactor: change validation state to have a static valid state

README.md, samples/LoginApp/ViewModels/SignUpViewModel.cs, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net472.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.netcoreapp3.1.approved.txt, src/ReactiveUI.Validation.Tests/ObservableValidationTests.cs, src/ReactiveUI.Validation.Tests/PropertyValidationTests.cs, src/ReactiveUI.Validation.Tests/ValidationBindingTests.cs, src/ReactiveUI.Validation/Comparators/ValidationStateComparer.cs, src/ReactiveUI.Validation/Components/Abstractions/IValidationComponent.cs, src/ReactiveUI.Validation/Components/BasePropertyValidation.cs, src/ReactiveUI.Validation/Components/ModelObservableValidation.cs, src/ReactiveUI.Validation/Components/ObservableValidation.cs, src/ReactiveUI.Validation/Contexts/ValidationContext.cs, src/ReactiveUI.Validation/Extensions/ValidatableViewModelExtensions.cs, src/ReactiveUI.Validation/Extensions/ValidationContextExtensions.cs, src/ReactiveUI.Validation/Helpers/ReactiveValidationObject.cs, src/ReactiveUI.Validation/Helpers/ValidationHelper.cs, src/ReactiveUI.Validation/States/IValidationState.cs, src/ReactiveUI.Validation/States/ValidationState.cs, src/ReactiveUI.Validation/TemplateGenerators/PropertyValidationGenerator.cs, src/ReactiveUI.Validation/TemplateGenerators/PropertyValidationGenerator.tt, src/ReactiveUI.Validation/ValidationBindings/ValidationBinding.cs
This PR implements the API specification eloquently argued and formulated by @thargy in https://github.com/reactiveui/ReactiveUI.Validation/issues/123#issue-721810174
Currently, there is no way to customize a `ValidationState`.
Also, there is no `ValidationRule` overload accepting a `ValidationState`.
See https://github.com/reactiveui/ReactiveUI.Validation/issues/123 for more information regarding this topic.
Now, we are using `IValidationState` where possible, and this simplifies the use of complex and extended validation rules. Now we have two more overloads for the `ValidationRule` extension method, one of the rules accepts a view model and `IObservable<IValidationState>`, …
=> feature: Use IValidationState Instead of ValidationState

src/ReactiveUI.Validation.AndroidSupport/ReactiveUI.Validation.AndroidSupport.csproj, src/ReactiveUI.Validation.AndroidX/ReactiveUI.Validation.AndroidX.csproj
In this PR we are referencing main `ReactiveUI.AndroidSupport` and `ReactiveUI.AndroidX` packages https://github.com/reactiveui/ReactiveUI.Validation/pull/134#discussion_r507110971 Also, this PR customizes the descriptions of the new `ReactiveUI.Validation.AndroidX` and `ReactiveUI.Validation.AndroidSupport` packages.
Currently, the packages have no unique descriptions and aren't referencing the main ReactiveUI Android support packages.
Now, the descriptions are updated, and the references are added.
Nothing.
=> housekeeping: Reference ReactiveUI.Android*, Customize Descriptions

README.md
This PR updates our `README.md` with additional documentation related to `AndroidX` and `AndroidSupport`.
Currently, there is no info in `README.md` describing the features introduced in https://github.com/reactiveui/ReactiveUI.Validation/pull/134
Now, the changes and new packages are documented. Ideally, a new 1.8 release should be published after merging this PR.
Those folks who are using `ReactiveUI.Validation` on `MonoAndroid90` will have to install one of the new packages:
- `ReactiveUI.Validation.AndroidSupport`
- `ReactiveUI.Validation.AndroidX`
Closes https://github.com/reactiveui/ReactiveUI.Validation/issues/129
=> housekeeping: Mention the New Android Packages

src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net472.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.netcoreapp3.1.approved.txt, src/ReactiveUI.Validation.Tests/ValidationBindingTests.cs, src/ReactiveUI.Validation.Tests/ValidationTextTests.cs, src/ReactiveUI.Validation/Collections/ValidationText.cs, src/ReactiveUI.Validation/Components/BasePropertyValidation.cs, src/ReactiveUI.Validation/Components/ModelObservableValidation.cs, src/ReactiveUI.Validation/Components/ObservableValidation.cs, src/ReactiveUI.Validation/Contexts/ValidationContext.cs, src/ReactiveUI.Validation/Helpers/ReactiveValidationObject.cs, src/ReactiveUI.Validation/ReactiveUI.Validation.csproj, src/ReactiveUI.Validation/States/ValidationState.cs, src/ReactiveUI.Validation/TemplateGenerators/PropertyValidationGenerator.cs, src/ReactiveUI.Validation/TemplateGenerators/PropertyValidationGenerator.tt
This pull request fixes #142 and implements #141.  There is no good reason for `ValidationText` to be mutable, as the current mutators (`Add` and `Clear`) are not used by the library and introduce potential thread-safety issues when validating asynchronously.
#142 describes a bug based on the nullability of `ReactiveValidationObject.SelectInvalidPropertyValidations`, the fix is included in this PR as it is dependent on changes implemented for #141
#141 describes the benefits of making `ValidationText` immutable.  As well as thread-safety, we can provide the `ValidationText.Empty` and `ValidationText.None` singletons for improved performance and memory utilisation.  The current behaviour creates a lot of …
=> Fixes ReactiveValidationObject NullReferenceException and enhances performance and thread-safety of ValidationText

src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net472.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.netcoreapp3.1.approved.txt, src/ReactiveUI.Validation.Tests/ValidationBindingTests.cs, src/ReactiveUI.Validation/Extensions/ValidatableViewModelExtensions.cs
Resolves #147, adding two new overloads of `ValidationRule` to make it easier to consumer observables of objects/structs that implement `IValidationState`.
Currently, you need to cast items in such observables to the interface explicitly.
The extension methods now accept both `IObservable<IValidationState>` and `IObservable<TValue>` where `TValue` implement `IValidationState`.  This means they now accept `IObservable<ValidationState>` implicitly.
This is purely an enhancement and doesn't break existing code.
=> feature: Add ValidationRule extensions method overloads to accept any object implementing IValidationState

README.md
This PR adds two images showing how native validations may look like on Android and on desktops via `INotifyDataErrorInfo`.
Currently, there are no images, and the benefits of using `ReactiveUI.Validation.AndroidX` and `iNotifyDataErrorInfo` are unclear.
Now, the images are added, showing the native validation behavior on Android, and the validation behavior on desktop platforms via `INotifyDataErrorInfo`. The images are taken from our [cross-platform sample app](https://github.com/reactiveui/ReactiveUI.Validation/tree/main/samples), from LoginApp.Android and LoginApp.Avalonia projects.
Nothing, this is just a minor README.md update.
=> housekeeping: Add Images to README.md

src/ReactiveUI.Validation/Collections/ValidationText.cs
This PR corrects the `ValidationText` error message. Guessing the message was accidentally made as misleading. Also, in the scope of this PR, we are intending to use the opportunity to ship a new `1.8.x` build to NuGet.
=> housekeeping: Correct ValidationText Error Message

src/ReactiveUI.Validation.AndroidSupport/Extensions/ViewForExtensions.cs, src/ReactiveUI.Validation.AndroidX/Extensions/ViewForExtensions.cs, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net472.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.netcoreapp3.1.approved.txt, src/ReactiveUI.Validation.Tests/Models/TestView.cs, src/ReactiveUI.Validation.Tests/ValidationBindingTests.cs, src/ReactiveUI.Validation/Extensions/ViewForExtensions.cs
This PR changes our nullability annotations to allow passing null view models to `BindValidation`. This could be potentially useful in cases when the view model is initialized after the control is activated, or when a view model is replaced with another view model after activation etc.
Currently, we don't use the `viewModel` parameter in `BindValidation`, but check if it is `null` and throw `ANE` if it is null.
Now, we support delayed view model initialization and just don't throw when `BindValidation` is called.
Nothing.
=> feature: Allow the ViewModel to be Null in BindValidation

src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net472.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.netcoreapp3.1.approved.txt, src/ReactiveUI.Validation.Tests/Models/IndeiTestViewModel.cs, src/ReactiveUI.Validation.Tests/NotifyDataErrorInfoTests.cs, src/ReactiveUI.Validation/Helpers/ReactiveValidationObject.cs
Currently, our `INotifyDataErrorInfo` implementation doesn't support custom formatters. The support for custom validation text formatters might be useful in cases when one needs to implement localization in their application via passing resource keys to `ValidationRule` calls instead of validation messages.
Currently, there is no way to customize messages emitted by `INotifyDataErrorInfo`.
Now, in order to customize the messages emitted by `INotifyDataErrorInfo`, one needs to either pass an instance of a custom `IValidationTextFormatter<string>` to `ReactiveValidationObject` constructor, or to register a default `IValidationTextFormatter<string>` globally via …
=> feature: Custom Formatters in ReactiveValidationObject

README.md
This PR documents custom validation text formatters. We describe how to use `SingleLineFormatter` with other separator characters, and also we describe how to override the default `IValidationTextFormatter<string>` used in ReactiveUI.Validation.
Currently, the way to override the default `IValidationTextFormatter<string>` isn't documented.
Now, the way to override the default `IValidationTextFormatter<string>` is documented.
Nothing.
=> housekeeping: Improve Custom Formatters Docs

.github/workflows/build-samples.yml
This PR attempts to fix the CI build errors that dependabot hits while trying to update stuff. Based on https://github.com/reactiveui/ReactiveUI.Validation/pull/188#issuecomment-749462434
=> housekeeping: Clean NuGet Locals before CI Build

.github/workflows/build-samples.yml
Planning to continue https://github.com/reactiveui/ReactiveUI.Validation/pull/190#issuecomment-749474150 investigation in this PR. This PR actually removes `/maxcpucount` from `Restore/Build the sample` task. Planning to rerun the CI a couple of times to verify.
=> fix: Remove maxcpucount from GitHub Actions

samples/Directory.build.props, samples/LoginApp.Avalonia/LoginApp.Avalonia.csproj, samples/LoginApp.Avalonia/Program.cs, samples/LoginApp.Forms.Android/LoginApp.Forms.Android.csproj, samples/LoginApp.Forms/LoginApp.Forms.csproj
This PR updates the dependencies of the `ReactiveUI.Validation` sample app `LoginApp`. Here we are helping dependabot to bump package versions. Also, now we use the new Avalonia 0.10.0 `AppBuilder` APIs. This PR shouldn't break anything.
=> deps: Update Dependencies

samples/LoginApp.Avalonia/LoginApp.Avalonia.csproj, samples/LoginApp.Avalonia/Views/SignUpView.xaml, samples/LoginApp.Avalonia/Views/SignUpView.xaml.cs
This PR incorporates [Avalonia.NameGenerator](https://github.com/avaloniaui/avalonia.namegenerator) package that allows us to use ReactiveUI code-behind bindings and ReactiveUI.Validation bindings without writing any boilerplate code. This source generator generates strongly typed references to named Avalonia controls declared in XAML files, at compile time (almost like WPF or Windows.Forms do). 
We are mixing ReactiveUI markup bindings and code-behind bindings in `LoginApp.Avalonia`.
Also, we are writing `FindControl` getters by hand in the `.xaml.cs` file of our view class.
The bindings in our updated Avalonia sample app should look pretty concise now, and we no longer have to …
=> feature: Use ReactiveUI bindings in the Avalonia sample app

README.md
It's a README.md update to clarify how `INotifyDataErrorInfo` support works.
Current doc is too general in `INotifyDataErrorInfo` area and can be misleading for new users of the ReactiveUI and the ReactiveUI.Validtaion. There is a question about it #237.
Note added to README.md, that `INotifyDataErrorInfo` requires regular binding in WPF.
Nothing.
=> Update README.md by adding additional note about INotifyDataErrorInfo support

samples/LoginApp.Android/LoginApp.Android.csproj, samples/LoginApp.Forms.Android/LoginApp.Forms.Android.csproj, samples/LoginApp.Forms/LoginApp.Forms.csproj, samples/LoginApp.Uwp/LoginApp.Uwp.csproj, samples/LoginApp.WinForms/LoginApp.WinForms.csproj, samples/LoginApp.Wpf/LoginApp.Wpf.csproj, samples/LoginApp/LoginApp.csproj, src/ReactiveUI.Validation.AndroidSupport/Extensions/ViewForExtensions.cs, src/ReactiveUI.Validation.AndroidSupport/ReactiveUI.Validation.AndroidSupport.csproj, src/ReactiveUI.Validation.AndroidX/Extensions/ViewForExtensions.cs, src/ReactiveUI.Validation.AndroidX/ReactiveUI.Validation.AndroidX.csproj, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net461.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net472.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net5.0.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.netcoreapp3.1.approved.txt, src/ReactiveUI.Validation/Components/BasePropertyValidation.cs, src/ReactiveUI.Validation/Contexts/ValidationContext.cs, src/ReactiveUI.Validation/Extensions/ValidatableViewModelExtensions.cs, src/ReactiveUI.Validation/Extensions/ViewForExtensions.cs, src/ReactiveUI.Validation/Helpers/ValidationHelper.cs, src/ReactiveUI.Validation/ReactiveUI.Validation.csproj, src/ReactiveUI.Validation/ValidationBindings/ValidationBinding.cs
This PR bumps dependencies. Also planning to fix nullability annotations soon so keeping this a draft temporary.
=> deps: Use ReactiveUI 14.*

src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net461.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net472.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net5.0.approved.txt, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.netcoreapp3.1.approved.txt, src/ReactiveUI.Validation/Contexts/ValidationContext.cs
This PR fixes the` ValidationContext.Text` property nullability issue discovered in the newest versions of the .NET SDK.
Currently, our CI build is [broken](https://github.com/reactiveui/ReactiveUI.Validation/runs/3388854682).
`
Error: D:\a\ReactiveUI.Validation\ReactiveUI.Validation\src\ReactiveUI.Validation\Contexts\ValidationContext.cs(82,31): error CS8619: Nullability of reference types in value of type 'ObservableAsPropertyHelper<ValidationText?>' doesn't match target type 'ObservableAsPropertyHelper<ValidationText>'. [D:\a\ReactiveUI.Validation\ReactiveUI.Validation\src\ReactiveUI.Validation\ReactiveUI.Validation.csproj]
`
From now on, the build is no longer broken.
**What …
=> fix: ValidationContext.ValidationText Nullability

src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net6.0.approved.txt, src/ReactiveUI.Validation.Tests/ReactiveUI.Validation.Tests.csproj, src/ReactiveUI.Validation/ReactiveUI.Validation.csproj
This is a breaking change to bring in line with ReactiveUI
* Net6 instead of Net5. Net5 support is later in the year and NuGet packages from Microsoft are not being released anymore with net 5 targets
* Net461 support is being dropped in a couple of months. Net462 is now the minimum.
=> breaking: Remove net5 support, use net6 instead

.github/workflows/ci-build.yml, .github/workflows/release.yml, src/Directory.build.props, src/ReactiveUI.Validation.AndroidSupport/ReactiveUI.Validation.AndroidSupport.csproj, src/ReactiveUI.Validation.AndroidX/ReactiveUI.Validation.AndroidX.csproj, src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net6.0.approved.txt, src/ReactiveUI.Validation/ReactiveUI.Validation.csproj, version.json
Update
**What is the current behaviour?**
Old targets
**What is the new behaviour?**
Add MonoAndroid12.0 and MonoAndroid13.0
Add Net 7.0
Update uap10.0.16299 to uap10.0.17763
Non expected
**Please check if the PR fulfils these requirements**
=> Housekeeping Remove Unsupported Targets

src/Directory.build.props, src/ReactiveUI.Validation.Tests/ReactiveUI.Validation.Tests.csproj, src/ReactiveUI.Validation/Collections/ReadOnlyCollectionPooled.cs, src/ReactiveUI.Validation/Collections/ValidationText.cs, src/ReactiveUI.Validation/Components/BasePropertyValidation.cs, src/ReactiveUI.Validation/Components/ObservableValidation.cs, src/ReactiveUI.Validation/Contexts/ValidationContext.cs, src/ReactiveUI.Validation/Helpers/ReactiveValidationObject.cs, src/ReactiveUI.Validation/ReactiveUI.Validation.csproj, src/global.json
Fix
Xamarin does not support System.Text.Json due to the inclusion of System.Buffers, Xamarin falls back to Netstandard2.0 within the package causing the System.Buffers lib to load
Xamarin targets use ReactiveUI 19.5.1 other targets use 19.5.31
None known
=> Fix issue when using ReactiveUI 19.5.31 which includes System.Text.Json

src/Directory.build.props, src/ReactiveUI.Validation.AndroidX/Extensions/ViewForExtensions.cs
update
AndroidX project has an Obsolete method
Remove Obsolete method
None
=> Housekeeping clean up Android X project

src/ReactiveUI.Validation.AndroidX/ReactiveUI.Validation.AndroidX.csproj, src/ReactiveUI.Validation/ReactiveUI.Validation.csproj, src/global.json, version.json
=> Housekeeping Update Version
